from __future__ import annotations

import json
import logging
import re
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from pydantic import ValidationError

from Skin_research_agents import evidence_chain, synthesis_chain
from Skin_research_tools import (
    VisionAnalysisError,
    analyze_skin_image,
    analyze_skin_video,
    medical_web_search,
    research_paper_search,
)
from common.contracts import Evidence, ResearchState, Source

load_dotenv()
logger = logging.getLogger(__name__)

_DISCLAIMER = (
    "This report is generated by an AI research assistant for educational purposes only. "
    "It is not a medical diagnosis and does not replace a professional in-person "
    "dermatological evaluation. Always consult a licensed dermatologist for an accurate "
    "diagnosis and personalised treatment plan."
)

# Bounds the research payload sent to the synthesis model. This is independent of the
# synthesis provider/model context window and should be tuned via evaluation, not a stale model name.
_MAX_RESEARCH_CHARS = 7_000


def _extract_sources(raw_text: str) -> list[dict[str, str]]:
    """Parse Tavily's block-oriented output without cross-pairing unrelated titles and URLs."""
    if not raw_text or not raw_text.strip():
        return []

    sources: list[dict[str, str]] = []
    for block in re.split(r"\n\s*-{4,}\s*\n", raw_text.strip()):
        title_match = re.search(r"^(?:Title|Paper):\s*(.+)$", block, flags=re.MULTILINE)
        url_match = re.search(r"^URL:\s*(https?://\S+)$", block, flags=re.MULTILINE)
        if not title_match or not url_match:
            continue
        url = url_match.group(1).rstrip(".,);]")
        title = title_match.group(1).strip()
        try:
            Source(title=title, url=url)
        except ValidationError:
            logger.warning("Skipping malformed research source: %r", url)
            continue
        sources.append({"title": title, "url": url})

    # Dedupe while preserving provider order.
    unique: dict[str, dict[str, str]] = {}
    for source in sources:
        unique.setdefault(source["url"], source)
    return list(unique.values())


def _safe_json_parse(raw: str) -> dict[str, Any]:
    """Parse JSON emitted by the evidence chain, tolerating accidental fences/whitespace."""
    if not raw or not raw.strip():
        return {}
    cleaned = raw.strip().replace("```json", "").replace("```", "").strip()
    try:
        value = json.loads(cleaned)
    except json.JSONDecodeError:
        # Recover a single JSON object if the provider wrapped it in prose.
        match = re.search(r"\{.*\}", cleaned, flags=re.DOTALL)
        if not match:
            return {}
        try:
            value = json.loads(match.group(0))
        except json.JSONDecodeError:
            return {}
    return value if isinstance(value, dict) else {}


def _normalize_evidence(raw: dict[str, Any], source_count: int, has_papers: bool) -> Evidence:
    payload = dict(raw)
    payload["source_count"] = max(0, source_count)
    payload["has_peer_reviewed"] = bool(payload.get("has_peer_reviewed", has_papers))
    try:
        return Evidence.model_validate(payload)
    except ValidationError:
        return Evidence(
            evidence_level="moderate" if has_papers else "limited",
            evidence_reason="Evidence grading could not be completed automatically.",
            source_count=source_count,
            has_peer_reviewed=has_papers,
            confidence_note="Please consult a licensed dermatologist for a professional evaluation.",
        )


def _fallback_report(patient_query: str, visual_analysis: str) -> str:
    """Produce a useful local report when synthesis is unavailable."""
    return (
        "VISUAL OBSERVATIONS\n"
        f"{visual_analysis}\n\n"
        "POTENTIAL CONDITIONS\n"
        "The available information is not sufficient to identify a condition. Several skin problems can look similar, so these observations should be reviewed by a licensed dermatologist rather than treated as a diagnosis.\n\n"
        "RECOMMENDATIONS\n"
        "Keep the area gently clean, avoid squeezing or scratching lesions, and stop new or irritating products until the skin settles. Use a bland fragrance-free moisturizer and protect the area from sun exposure. Do not start prescription treatment without an in-person clinical assessment.\n\n"
        "WHEN TO SEE A DOCTOR\n"
        "Arrange prompt medical review for severe pain, rapidly spreading redness, fever, pus, swelling near the eye, vision changes, blistering, or symptoms that persist or worsen. Patient description: "
        f"{patient_query}"
    )


def _run_searches(search_query: str, paper_query: str) -> tuple[str, str]:
    """Run the independent web and paper searches concurrently."""
    results = {"web": "", "papers": ""}
    with ThreadPoolExecutor(max_workers=2, thread_name_prefix="research-search") as executor:
        futures = {
            executor.submit(medical_web_search.invoke, search_query): "web",
            executor.submit(research_paper_search.invoke, paper_query): "papers",
        }
        for future in as_completed(futures):
            kind = futures[future]
            try:
                results[kind] = future.result()
                logger.info("[Research] %s search complete", kind)
            except Exception as exc:
                logger.warning("[Research] %s search failed: %s", kind, exc)
    return results["web"], results["papers"]


def run_skin_research_pipeline(
    patient_query: str,
    image_path: str | Path | None = None,
    video_path: str | Path | None = None,
) -> dict[str, Any]:
    """Run the full research pipeline and validate its public response contract."""
    patient_query = patient_query.strip()
    if not patient_query:
        raise ValueError("patient_query must not be empty")

    state: dict[str, Any] = {
        "query": patient_query,
        "visual_analysis": "",
        "visual_analysis_available": False,
        "visual_analysis_error": None,
        "report": "",
        "report_generated_by": "pending",
        "report_error": None,
        "sources": [],
        "research_papers": [],
        "evidence": {},
        "disclaimer": _DISCLAIMER,
    }

    logger.info("[Research] Step 1 — Visual skin media analysis")
    if video_path:
        media_to_analyze = video_path
        media_type = "video"
    elif image_path:
        media_to_analyze = image_path
        media_type = "image"
    else:
        media_to_analyze = None
        media_type = None

    if media_to_analyze and media_type:
        try:
            analyzer = analyze_skin_video if media_type == "video" else analyze_skin_image
            state["visual_analysis"] = analyzer(media_to_analyze, patient_query)
            state["visual_analysis_available"] = bool(state["visual_analysis"].strip())
            logger.info("[Research] %s analysis complete (%d chars)", media_type.capitalize(), len(state["visual_analysis"]))
        except Exception as exc:
            state["visual_analysis_error"] = exc.code if isinstance(exc, VisionAnalysisError) else "vision_provider_error"
            logger.warning("[Research] %s analysis failed — continuing text-only: %s", media_type, exc)
            state["visual_analysis"] = (
                f"{media_type.capitalize()} analysis could not be completed. The report below uses the written description only. "
                f"Diagnostic status: {state['visual_analysis_error']}."
            )
    else:
        state["visual_analysis_error"] = "no_media"
        state["visual_analysis"] = f"No image or video was provided. The report below uses the written description only. Patient description: {patient_query}"

    logger.info("[Research] Step 2 — Medical web search and paper search")
    visual_excerpt = state["visual_analysis"][:250]
    search_query = f"skin condition {patient_query} symptoms diagnosis treatment dermatology {visual_excerpt}".strip()
    paper_query = f"{patient_query} dermatology skin condition clinical study"
    web_results_raw, paper_results_raw = _run_searches(search_query, paper_query)

    # RAG Vector Store Retrieval
    rag_guidelines = []
    try:
        from common.dermatology_rag import get_dermatology_rag
        rag_guidelines = get_dermatology_rag().query(f"{patient_query} {visual_excerpt}", top_k=3)
        logger.info("[Research] Retrieved %d clinical RAG guidelines", len(rag_guidelines))
    except Exception as rag_err:
        logger.warning("[Research] RAG retrieval failed: %s", rag_err)

    state["rag_guidelines"] = rag_guidelines
    state["sources"] = _extract_sources(web_results_raw)
    state["research_papers"] = _extract_sources(paper_results_raw)

    rag_lines = []
    for guideline in rag_guidelines:
        category = guideline.get("category", "Guideline")
        title = guideline.get("title", "")
        content = guideline.get("content", "")
        rag_lines.append(f"- [{category}] {title}: {content}")
    rag_text = "\n".join(rag_lines)
    combined_research = f"CLINICAL GUIDELINES (RAG):\n{rag_text}\n\nMEDICAL SOURCES:\n{web_results_raw}\n\nRESEARCH PAPERS:\n{paper_results_raw}"[:_MAX_RESEARCH_CHARS]

    logger.info("[Research] Step 3 — Synthesising report")
    try:
        state["report"] = synthesis_chain.invoke({
            "query": patient_query,
            "visual_analysis": state["visual_analysis"],
            "research_data": combined_research,
        })
        state["report_generated_by"] = "provider"
        logger.info("[Research] Report synthesised (%d chars)", len(state["report"]))
    except Exception as exc:
        logger.error("[Research] Synthesis chain failed: %s", exc)
        state["report_generated_by"] = "local_fallback"
        state["report_error"] = "synthesis_provider_error"
        state["report"] = _fallback_report(patient_query, state["visual_analysis"])

    logger.info("[Research] Step 4 — Grading evidence quality")
    all_sources = state["sources"] + state["research_papers"]
    try:
        raw_evidence = evidence_chain.invoke({"report": state["report"], "sources": json.dumps(all_sources)})
        parsed = _safe_json_parse(raw_evidence)
        if not parsed:
            raise ValueError("Empty evidence JSON")
    except Exception as exc:
        logger.warning("[Research] Evidence grading failed — using fallback: %s", exc)
        parsed = {}

    state["evidence"] = _normalize_evidence(parsed, len(all_sources), bool(state["research_papers"])).model_dump(mode="json")

    validated = ResearchState.model_validate(state)
    return validated.model_dump(mode="json")
