"""
Localization module for AI Skin Specialist.
Provides dynamic Accept-Language header parsing and language-specific prompt directives.
"""

from typing import Dict, Optional

# Supported language codes mapped to their display names and prompt directives
SUPPORTED_LANGUAGES: Dict[str, Dict[str, str]] = {
    "en": {
        "name": "English",
        "directive": "Respond clearly and professionally in English.",
        "disclaimer": "This report is generated by an AI assistant for informational purposes only and does not constitute a formal medical diagnosis."
    },
    "es": {
        "name": "Spanish (Español)",
        "directive": "Responde de manera clara, profesional y empática en español.",
        "disclaimer": "Este informe es generado por un asistente de IA solo con fines informativos y no constituye un diagnóstico médico formal."
    },
    "fr": {
        "name": "French (Français)",
        "directive": "Répondez clairement, de manière professionnelle et empathique en français.",
        "disclaimer": "Ce rapport est généré par un assistant IA à des fins d'information uniquement et ne constitue pas un diagnostic médical formel."
    },
    "de": {
        "name": "German (Deutsch)",
        "directive": "Antworten Sie klar, professionell und empathisch auf Deutsch.",
        "disclaimer": "Dieser Bericht wird von einem KI-Assistenten nur zu Informationszwecken erstellt und stellt keine formelle medizinische Diagnose dar."
    },
    "ar": {
        "name": "Arabic (العربية)",
        "directive": "أجب بوضوح ومهنية وتعاطف باللغة العربية.",
        "disclaimer": "تم إنشاء هذا التقرير بواسطة مساعد ذكاء اصطناعي لأغراض إعلامية فقط ولا يشكل تشخيصًا طبيًا رسميًا."
    },
    "hi": {
        "name": "Hindi (हिंदी)",
        "directive": "हिंदी में स्पष्ट, पेशेवर और सहानुभूतिपूर्ण उत्तर दें।",
        "disclaimer": "यह रिपोर्ट केवल जानकारी के उद्देश्यों के लिए एक AI सहायक द्वारा तैयार की गई है और यह औपचारिक चिकित्सा निदान नहीं है।"
    },
    "ur": {
        "name": "Urdu (اردو)",
        "directive": "اردو میں واضح، پیشہ ورانہ اور ہمدردانہ جواب دیں۔",
        "disclaimer": "یہ رپورٹ صرف معلوماتی مقاصد کے لیے ایک AI اسسٹنٹ کے ذریعے تیار کی گئی ہے اور یہ باقاعدہ طبی تشخیص نہیں ہے۔"
    },
    "zh": {
        "name": "Chinese (中文)",
        "directive": "请用中文清晰、专业且富有同理心地回答。",
        "disclaimer": "本报告由人工智能助手生成，仅供参考，不构成正式的医疗诊断。"
    }
}

DEFAULT_LANGUAGE = "en"


def parse_accept_language(accept_language_header: Optional[str]) -> str:
    """
    Parse an HTTP Accept-Language header string and return the best matching supported language code.
    Example header: 'es-ES,es;q=0.9,en-US;q=0.8,en;q=0.7' -> 'es'
    """
    if not accept_language_header:
        return DEFAULT_LANGUAGE

    # Split header by comma
    languages = accept_language_header.split(",")
    for item in languages:
        # Extract main language tag e.g. 'es-ES' -> 'es'
        tag = item.split(";")[0].strip().lower()
        primary_code = tag.split("-")[0]
        if primary_code in SUPPORTED_LANGUAGES:
            return primary_code

    return DEFAULT_LANGUAGE


def get_localized_directive(lang_code: str) -> str:
    """
    Retrieve the prompt directive for the target language.
    """
    lang = SUPPORTED_LANGUAGES.get(lang_code, SUPPORTED_LANGUAGES[DEFAULT_LANGUAGE])
    return lang["directive"]


def get_localized_disclaimer(lang_code: str) -> str:
    """
    Retrieve the medical disclaimer in the target language.
    """
    lang = SUPPORTED_LANGUAGES.get(lang_code, SUPPORTED_LANGUAGES[DEFAULT_LANGUAGE])
    return lang["disclaimer"]


def get_language_name(lang_code: str) -> str:
    """
    Get human-readable display name for a language code.
    """
    lang = SUPPORTED_LANGUAGES.get(lang_code, SUPPORTED_LANGUAGES[DEFAULT_LANGUAGE])
    return lang["name"]
